brithmasoft/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employment_agent.urls'))
]

employment_agent/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf.urls.static import static

urlpatterns = [
    path('', employer_agent, name="home"),
    path("employers/", EmployersList.as_view(), name="employers"),
    path("employers/create/", EmployerCreateView.as_view(), name="create-employer"),
    path("employers/<pk>/delete/",
         EmployerDeleteView.as_view(), name="delete-employer"),
    path("employers/<pk>/", EmployerDetailView.as_view(), name="view-employer"),
    path("employers/<pk>/update/",
         EmployerUpdateView.as_view(), name="edit-employer"),
    path('employers/search/<page>/', search_employers, name="search-employers"),
    path("job_seekers/", JobSeekersList.as_view(), name="job-seekers"),
    path("job_seekers/create/", JobSeekerCreateView.as_view(),
         name="create-job-seeker"),
    path("job_seekers/<pk>/", JobSeekerDetailView.as_view(), name="view-job-seeker"),
    path("job_seekers/<pk>/update/",
         JobSeekerUpdateView.as_view(), name="edit-job-seeker"),
    path("job_seekers/<pk>/delete/",
         JobSeekerDeleteView.as_view(), name="delete-job-seeker"),
    path('job_seekers/search/<page>/',
         search_job_seekers, name="search-job-seekers"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

employment_agent/models.py
from django.db import models
from .helpers import RandomFileName
# Create your models here.


class Employer(models.Model):
    firstname = models.CharField(max_length=45)
    lastname = models.CharField(max_length=45)
    phone_number = models.CharField(max_length=13)
    physical_address = models.CharField(max_length=255)
    email_address = models.EmailField(max_length=90)
    job_title = models.CharField(max_length=500)
    job_description = models.CharField(max_length=4000)
    status = models.BooleanField(default=False)
    date_needed = models.DateField()
    resume = models.FileField(upload_to=RandomFileName(
        "employer_files"), default="employer_files/Resume.docx")

    def __str__(self):
        return self.firstname + " " + self.lastname


class JobSeeker(models.Model):
    firstname = models.CharField(max_length=45)
    lastname = models.CharField(max_length=45)
    phone_number = models.CharField(max_length=13)
    email_address = models.EmailField(max_length=45)
    physical_address = models.CharField(max_length=255)
    job_title = models.CharField(max_length=500)
    description = models.CharField(max_length=4000)
    status = models.BooleanField(default=False)
    date_applied = models.DateField()
    resume = models.FileField(upload_to=RandomFileName(
        "job_seeker_files"), default="job_seeker_files/Resume.docx")

    def __str__(self):
        return self.firstname + " " + self.lastname

employment_agent/forms.py
from django import forms
from .models import *

# To be used with status field
TRUE_FALSE_CHOICES = (
    (True, 'Occupied'),
    (False, 'Vaccant')
)

EMPLOYED_UNEMPLOYED_CHOICES = (
    (True, 'Employed'),
    (False, 'Unemployed')
)

# The form for searching employers


class SearchEmployersForm(forms.Form):
    job_title = forms.CharField(max_length=500)
    status = forms.IntegerField()


class SearchJobSeekersForm(forms.Form):
    job_title = forms.CharField(max_length=500)
    status = forms.IntegerField()

# the form updating employer data


class EmployerForm(forms.ModelForm):
    status = forms.ChoiceField(choices=TRUE_FALSE_CHOICES, label="Status",
                               initial='', widget=forms.Select(), required=True)

    class Meta:
        model = Employer
        fields = ['firstname',
                  'lastname',
                  'phone_number',
                  'physical_address',
                  'email_address',
                  'job_title',
                  'job_description',
                  'status',
                  'date_needed',
                  'resume'
                  ]
        widgets = {
            'job_description': forms.Textarea(attrs={'rows': 5}),
            'firstname': forms.TextInput(attrs={'placeholder': 'Firstname'}),
            'lastname': forms.TextInput(attrs={'placeholder': 'Lastname'}),
            'phone_number': forms.TextInput(attrs={'placeholder': '+123456789012'}),
            'physical_address': forms.TextInput(attrs={'placeholder': '1234 Street 1'}),
            'email_address': forms.TextInput(attrs={'placeholder': 'jobseeker@example.com'}),
            'job_title': forms.TextInput(attrs={'placeholder': 'Job title'})
        }


class EmployerFilterForm(forms.Form):
    firstname = forms.CharField(max_length=45, required=False, widget=forms.TextInput(
        attrs={
            'placeholder': 'Firstname'
        }
    ))
    lastname = forms.CharField(max_length=45, required=False,
                               widget=forms.TextInput(attrs={
                                   'placeholder': 'Lastname'
                               })
                               )
    job_title = forms.CharField(max_length=255, required=False, widget=forms.TextInput(
        attrs={
            'placeholder': 'Job title'
        }
    ))
    status = forms.ChoiceField(choices=TRUE_FALSE_CHOICES, label="Status",
                               initial='', widget=forms.Select(), required=False)
    date_needed = forms.DateField(required=False)


class JobSeekerFilterForm(forms.Form):
    firstname = forms.CharField(max_length=45, required=False, widget=forms.TextInput(
        attrs={
            'placeholder': 'Firstname'
        }
    ))
    lastname = forms.CharField(max_length=45, required=False,
                               widget=forms.TextInput(attrs={
                                   'placeholder': 'Lastname'
                               })
                               )
    job_title = forms.CharField(max_length=255, required=False, widget=forms.TextInput(
        attrs={
            'placeholder': 'Job title'
        }
    ))
    status = forms.ChoiceField(choices=EMPLOYED_UNEMPLOYED_CHOICES, label="Status",
                               initial='', widget=forms.Select(), required=False)

    date_applied = forms.DateField(required=False)


class JobSeekerForm(forms.ModelForm):
    status = forms.ChoiceField(choices=EMPLOYED_UNEMPLOYED_CHOICES, label="Status",
                               initial='', widget=forms.Select(), required=True)

    class Meta:
        model = JobSeeker
        fields = ['firstname',
                  'lastname',
                  'phone_number',
                  'physical_address',
                  'email_address',
                  'job_title',
                  'status',
                  'date_applied',
                  'resume'
                  ]
        widgets = {
            'firstname': forms.TextInput(attrs={'placeholder': 'Firstname'}),
            'lastname': forms.TextInput(attrs={'placeholder': 'Lastname'}),
            'phone_number': forms.TextInput(attrs={'placeholder': '+123456789012'}),
            'physical_address': forms.TextInput(attrs={'placeholder': 'Street address'}),
            'email_address': forms.TextInput(attrs={'placeholder': 'jobseeker@example.com'}),
            'job_title': forms.TextInput(attrs={'placeholder': 'Job title'})
        }

employment_agent/views.py
import json
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.views.generic.detail import DetailView
from django.urls import reverse
from .models import *
from .forms import *
import re
from django.core import serializers
from django.core.paginator import Paginator, InvalidPage
from django.conf import settings

# Create your views here.


def employer_agent(request):
    context = {
        'nbar': 'home'
    }
    return render(request, "employment_agent/home.html", context)


def mobile(request):
    """Return true if the request comes from a mobile device"""
    MOBILE_AGENT_RE = re.compile(
        r".*(iphone|mobile|androidtouch)", re.IGNORECASE)
    if MOBILE_AGENT_RE.match(request.META['HTTP_USER_AGENT']):
        return True
    else:
        return False


class EmployersList(ListView):
    paginate_by = 10
    model = Employer
    context_object_name = "employers_list"
    template_name = "employment_agent/employers_index.html"
    ordering = ['date_needed']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        is_mobile = False
        if mobile(self.request):
            is_mobile = True
        context['is_mobile'] = is_mobile
        context['form'] = EmployerFilterForm()
        context['search_url'] = reverse('search-employers', kwargs={'page': 1})
        context['nbar'] = 'employers'
        return context

    def get_queryset(self):
        qs = self.model.objects.all()
        form = EmployerFilterForm(self.request.GET)
        # check if form is valid
        if form.is_valid():
            # now make a search based on the form
            # fields provided
            if form.cleaned_data['job_title']:
                qs = qs.filter(job_title__contains=form.cleaned_data['job_title'])
            if form.cleaned_data['status']:
                qs = qs.filter(status=form.cleaned_data['status'])
            if form.cleaned_data['firstname']:
                qs = qs.filter(firstname__contains=form.cleaned_data['firstname'])
            if form.cleaned_data['lastname']:
                qs = qs.filter(lastname__contains=form.cleaned_data['lastname'])

        return qs




class EmployerCreateView(CreateView):
    model = Employer
    form_class = EmployerForm

    # Redirect to view the newly created employer
    def get_success_url(self):
        return reverse('view-employer', kwargs={'pk': self.object.pk})


class EmployerDeleteView(DeleteView):
    model = Employer
    #template_name = "employment_agent/employer_confirm_delete.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.get_object().delete()
        payload = {"delete": "ok"}
        return HttpResponseRedirect(reverse("employers"))


class EmployerDetailView(DetailView):
    model = Employer
    context_object_name = "employer"
    template_name = "employment_agent/employer_details.html"


class EmployerUpdateView(UpdateView):
    model = Employer
    form_class = EmployerForm
    template_name_suffix = '_update_form'
    context_object_name = "employer"

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("view-employer", kwargs={"pk": pk})


# View for searching employers
def search_employers(request, page):
    if request.method == "POST":
        search_form = None
        if settings.TESTING:
            search_form = SearchEmployersForm(request.POST or None)
        else:
            form_data = json.loads(request.body)
            search_form = SearchEmployersForm(form_data or None)
        # Check if the form is valid
        if search_form.is_valid():
            # do the searching
            status = search_form.cleaned_data['status']
            if status == 1:
                status = True
            else:
                status = False

            job_title = search_form.cleaned_data['job_title']
            # save session data for the next search of the same type
            request.session['status'] = status
            request.session['job_title'] = job_title

            # want to search for employers with status and job_title that
            # matches the given query
            queryset = Employer.objects.filter(
                job_title__contains=job_title, status=status).order_by('job_title')

            # now paginate the data
            pages = Paginator(queryset, 10)

            # get the results
            results = pages.page(1)

            # json serialize the data
            data = serializers.serialize("json", results)
            content = {}
            content['data'] = data
            content['total_pages'] = pages.num_pages
            content['current_page'] = int(page)
            # set the next page to be viewed
            if results.has_next():
                content['next_page'] = 2

            return JsonResponse(content)
        else:
            response = JsonResponse({"message": "Please provide valid input"})
            response.status_code = 400
            return response
    else:
        # Request is a GET
        status = request.session.get('status', None)
        job_title = request.session.get('job_title', None)
        # Make a query
        queryset = Employer.objects.filter(
            job_title__contains=job_title, status=status).order_by('job_title')
        # Paginate
        pages = Paginator(queryset, 10)
        # get the results
        results = None
        try:
            results = pages.page(page)
        except InvalidPage:
            response = JsonResponse({"message": "Nothing found"})
            return response
        # set the content
        content = {}
        content['data'] = serializers.serialize("json", results)
        content['total_pages'] = pages.num_pages
        content['current_page'] = int(page)
        # set the next page to be viewed
        if results.has_next():
            content['next_page'] = int(page) + 1
        # set the previous page
        if results.has_previous():
            content['previous_page'] = int(page) - 1

        return JsonResponse(content)


# Job seeker list view
class JobSeekersList(ListView):
    paginate_by = 10
    model = JobSeeker
    context_object_name = "jobseekers_list"
    template_name = "employment_agent/job_seekers_index.html"
    ordering = ['date_applied']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        is_mobile = False
        if mobile(self.request):
            is_mobile = True
        context['is_mobile'] = is_mobile
        context['nbar'] = 'jobseekers'
        context['form'] = JobSeekerFilterForm()
        return context

    def get_queryset(self):
        qs = self.model.objects.all()
        form = JobSeekerFilterForm(self.request.GET)
        # check if form is valid
        if form.is_valid():
            # now make a search based on the form
            # fields provided
            if form.cleaned_data['job_title']:
                qs = qs.filter(job_title__contains=form.cleaned_data['job_title'])
            if form.cleaned_data['status']:
                qs = qs.filter(status=form.cleaned_data['status'])
            if form.cleaned_data['firstname']:
                qs = qs.filter(firstname__contains=form.cleaned_data['firstname'])
            if form.cleaned_data['lastname']:
                qs = qs.filter(lastname__contains=form.cleaned_data['lastname'])

        return qs



# Job seeker detail view
class JobSeekerDetailView(DetailView):
    model = JobSeeker
    context_object_name = "jobseeker"
    template_name = "employment_agent/job_seeker_details.html"

# Job seeker create view


class JobSeekerCreateView(CreateView):
    model = JobSeeker
    form_class = JobSeekerForm

    # Redirect to view the newly created job seeker
    def get_success_url(self):
        return reverse('view-job-seeker', kwargs={'pk': self.object.pk})


class JobSeekerUpdateView(UpdateView):
    model = JobSeeker
    form_class = JobSeekerForm
    template_name_suffix = '_update_form'
    context_object_name = "jobseeker"

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("view-job-seeker", kwargs={"pk": pk})

    '''
    def post(self, request, **kwargs):
        jobseeker_form = JobSeekerForm(request.POST, request.FILES)
        if jobseeker_form.is_valid():
            # First get the object referenced here
            jobseeker_form.save()
            # Redirect user to view the updated changes
            pk = int(self.kwargs["pk"])
            return HttpResponseRedirect(reverse("view-employer", kwargs={"pk": pk}))
        else:
            return render(request, "employment_agent/jobseeker_update_form.html", {"form": jobseeker_form})
    '''


class JobSeekerDeleteView(DeleteView):
    model = JobSeeker
    #template_name = "employment_agent/employer_confirm_delete.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.get_object().delete()
        payload = {"delete": "ok"}
        return HttpResponseRedirect(reverse("job-seekers"))


# View for searching job seekers
def search_job_seekers(request, page):
    if request.method == "POST":
        search_form = None
        if settings.TESTING:
            search_form = SearchJobSeekersForm(request.POST or None)
        else:
            form_data = json.loads(request.body)
            search_form = SearchJobSeekersForm(form_data or None)
        # Check if the form is valid
        if search_form.is_valid():
            # do the searching
            status = search_form.cleaned_data['status']
            if status == 1:
                status = True
            else:
                status = False

employment_agent/templates/employment_agent/base.html
<!DOCTYPE html>

<html>
{% load static %}
<head>
    <title>
    {% block title %}
       Employment agent
    {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'employment_agent/css/bootstrap.min.css'%}" />
    <link rel="stylesheet" href="{% static 'employment_agent/navbar.css'%}" />
    <link rel="stylesheet" href="{% static 'employment_agent/style.css'%}" />
    <link rel="stylesheet" href="{% static 'employment_agent/footer.css'%}" />
    <link rel="stylesheet" href="{% static 'employment_agent/jquery-ui/jquery-ui.css'%}" />
    <link rel="stylesheet" href="{% static 'employment_agent/jquery-ui/jquery-ui.theme.css'%}" />
    <script src="https://kit.fontawesome.com/02fe633b52.js" crossorigin="anonymous"></script>
    {% block extra_head %}
    {% endblock extra_head %}
</head>

<body>
    {% include "./components/navbar.html" %}
    <div class="container">
        {% block content %} {% endblock content%}
    </div>
    {% include "./components/footer.html" %}
    <script src="{% static 'employment_agent/jquery-3.5.1.js'%}"></script>
    <script src="{% static 'employment_agent/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'employment_agent/jquery-ui/jquery-ui.js'%}"></script>
    <script src="{% static 'employment_agent/employer.js'%}"></script>
    {% block extra_body %}
    {% endblock extra_body %}
</body>

</html>

employment_agent/templates/employment_agent/employer_confirm_delete.html
{% extends "./base.html" %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'employment_agent/employer_confirm_delete.css'%}" />
{% endblock %}

{% block content %}
<div class="container">
        <form id="employer-delete-dialog" method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" class="btn btn-primary" value="Confirm">
        </form>
    </div>
{% endblock %}

employment_agent/templates/employment_agent/employer_details.html
{% extends "./base.html" %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'employment_agent/employer_details.css'%}" />
{% endblock extra_head %}
{% block content %}
<div class="card my-3" style="width: 100%;">
  <div class="card-body">
    <h5 class="card-title">{{employer.job_title}}</h5>
    <h6 class="card-subtitle mb-2 text-muted">
     Status: {% if employer.status %}
                        <span class="badge badge-primary">Occupied</span>
                      {% else%}
                       <spa class="badge badge-success">Vaccant</span>
                      {% endif %}
    </h6>
    <p class="card-text">{{employer.job_description}}</p>
    <p class="card-text"><a class="card-link" href="{{employer.resume.url}}">Download document</a></p>
    <h6 class="card-subtitle mb-2 text-muted">
    Due date: {{employer.date_needed}}
    </h6>
    {% if user.is_superuser %}
    <p class="card-text"> Name: {{ employer.firstname }} {{ employer.lastname }}</p>
    <p class="card-text">Phone number: {{ employer.phone_number }}</p>
    <p class="card-text">Email: <a class="card-link" href="mailto:{{employer.email_address }}">{{employer.email_address }}</a></p>
    <p class="card-text">Physical address: {{employer.physical_address }}</p>
    <a href="{% url 'edit-employer' employer.pk %}" class="btn btn-primary">Edit</a>
    <a href="{% url 'delete-employer' employer.pk %}" class="btn btn-danger">Delete</a>
    {% endif %}
  </div>
</div>
{% endblock content %}
{% block extra_body %}
<script src="{% static 'employment_agent/employer_detail.js'%}"></script>
<script src="{% static 'employment_agent/employer_functions.js'%}"></script>
{% endblock extra_body %}

employment_agent/templates/employment_agent/employer_form.html
{% extends './base.html' %}
{% load widget_tweaks %}
{% block content %}
  <div class="container py-3">
        <form action="" enctype="multipart/form-data" method="post">
            <h3>Create employer</h3>
             {% csrf_token %}
             {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}

                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}
                        {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% endfor %}
            <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Save</button>
        </form>
    </div>
{% endblock %}

employment_agent/templates/employment_agent/employer_update_form.html
{% extends "./base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'employment_agent/employer_update.css'%}" />
{% endblock extra_head %} {% block content %}
<h1>Edit</h1>
<form id="employer-update" action="" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
       <div class="form-group">
        <label for="{{ field.id_for_label }}">{{field.label}}</label>
        {{ field | add_class:'form-control' }}
        {% for error in field.errors %}
          <span class="help-block">{{error}}</span>
        {% endfor %}
       </div>
    {% endfor %}
      <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Save</button>
</form>
{% endblock content %}

{% block extra_body %}
<script>
   $(function(){
     $( "#id_date_needed" ).datepicker();
   })
</script>
{% endblock extra_body %}

employment_agent/templates/employment_agent/employers_index.html
{% extends "./base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
  Employers
{% endblock %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'employment_agent/employers.css'%}" />
{% endblock extra_head %} {% block content %}
<div>
    <div class="row my-3">
        <div class="col-md-3" id="sticky-sidebar">
           <div class="card sticky-top my-2" style="width: 100%;" >
            <div class="card-body">
                <h5 class="card-title">Search </h5>
                <form>
                    {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}

                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}
                        {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-lg btn-block"><i class="fas fa-search"></i> Search</button>
                </form>
            </div>
           </div>
        </div>
        <div class="col-md-9 my-2">
            <a  href="{% url 'create-employer' %}" class="btn btn-primary"><i class="fas fa-plus"></i> Add new employer</a>
            {% for employer in employers_list %}
            <div class="card my-2" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title">{{employer.firstname}} {{employer.lastname}}</h5>
                    <h5>Job title: {{employer.job_title}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted"> Status:
                      {% if employer.status %}
                        <span class="badge badge-primary">Occupied</span>
                      {% else%}
                       <spa class="badge badge-success">Vaccant</span>
                      {% endif %}
                    </h6>
                    <p class="card-text">
                        {{employer.job_description}}
                    </p>

                    <h6 class="card-subtitle mb-2 text-muted">
                        Due date: {{employer.date_needed}}
                    </h6>
                    <a href="{% url 'view-employer' employer.pk  %}" class="btn btn-secondary">View</a> {% if user.is_superuser %}
                    <a href="{% url 'edit-employer' employer.pk %}" class="btn btn-secondary">Edit</a>
                    <a href="{% url 'delete-employer' employer.pk %}" class="btn btn-danger">Delete</a> {% endif %}
                </div>
            </div>
            {% endfor %}
            <!--Now the pagination section-->
            {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">

                <span id="previous-ref">
                    {% if page_obj.has_previous %}
                    <a class="btn btn-primary" href="/employers?page={{page_obj.previous_page_number}}"> &laquo; previous</a>
                    {% endif %}
                </span>

                <span class="page-current">
                    Page <span id="current-page">{{ page_obj.number }}</span> of <span id="total-pages">{{ page_obj.paginator.num_pages }}</span>.
                </span>

                <span id="next-ref">
                    {% if page_obj.has_next %}
                    <a class="btn btn-primary" href="/employers?page={{page_obj.next_page_number}}">next &raquo;</a>
                    {% endif %}
                </span>

                </span>
            </div>
        </div>
    </div>
</div>
{% else %}
{% endif %} {% endblock content %}

employment_agent/templates/employment_agent/home.html
{% extends "./base.html" %}
{% block content %}
<div class="container">
        <div class="nav-links text-center py-5">
            <a class="btn btn-lg btn-primary" id="go-to-job-seekers" href="{% url 'job-seekers' %}">Job seekers</a>
            <a class ="btn btn-lg btn-primary" id="go-to-employers" href="{% url 'employers' %}">Employers</a>
        </div>
</div>
{% endblock %}

employment_agent/templates/employment_agent/job_seeker_details.html
{% extends "./base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'employment_agent/employers.css'%}" />
{% endblock extra_head %}
{% block content %}
<div class="py-3">
 <table class="table">
            <tbody>
                <tr><td><b>Firstname:</b></td>
                    <td>{{jobseeker.firstname}}</td>
                </tr>
                <tr><td><b>Lastname:</b></td>
                    <td>{{jobseeker.lastname}}</td>
                </tr>
                <tr><td><b>Job title:</b></td>
                    <td>{{jobseeker.job_title}}</td>
                </tr>
                <tr><td><b>Phone number:</b></td>
                    <td>{{jobseeker.phone_number}}</td>
                </tr>
                <tr><td><b>Email address:</b></td>
                    <td>{{jobseeker.email_address}}</td>
                </tr>
                <tr><td><b>Status:</b></td>
                    <td id="status">{{jobseeker.status}}</td>
                </tr>
                <tr><td><b>Date needed:</b></td>
                    <td>{{jobseeker.date_applied}}</td>
                </tr>
            </tbody>
        </table>

        <div class="attachments">

        </div>
        <div class="controls">
            <a class="btn btn-primary" href="{% url 'edit-job-seeker' jobseeker.pk %}">Edit</a>
            <a class="btn btn-danger" href="{% url 'delete-job-seeker' jobseeker.pk %}">Delete</a>
        </div>
    </div>
    </div>
    {% endblock content %}

    {% block extra_body %}
    <script src="{% static 'employment_agent/jobseeker_detail.js'%}"></script>
    <script src="{% static 'employment_agent/jobseeker_functions.js'%}"></script>
    {% endblock extra_body %}

employment_agent/templates/employment_agent/jobseeker_confirm_delete.html
{% extends "./base.html" %}
{% load static %}
{% block extra_head %}
 <link rel="stylesheet" href="{% static 'employment_agent/jobseeker_confirm_delete.css' %}" />
{% endblock extra_head %}
{% block content %}
<div class="py-3">
 <form class="text-center" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class="btn btn-primary" type="submit" value="Confirm"/>
</form>
</div>
{% endblock content %}

employment_agent/templates/employment_agent/jobseeker_form.html
{% extends "./base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'employment_agent/jobseeker_update.css'%}" />
{% endblock extra_head %}
{% block content %}
<div class="my-3">
<form action="" enctype="multipart/form-data" method="post">
            <h3>Create job seeker data</h3>
             {% csrf_token %}
             {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}

                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}
                        {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% endfor %}
          <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Save</button>
        </form>
</div>
{% endblock content %}